services:
  traefik:
    image: traefik:v3.3.5
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api=true
      - --api.dashboard=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      "traefik.enable": 'true'
      "traefik.http.routers.traefik.entrypoints": "web"
      "traefik.http.routers.traefik.rule": "Host(`localhost.local`)"
      "traefik.http.routers.traefik.service": "api@internal"
      "traefik.http.middlewares.traefik-dashboard-auth.basicauth.users": "${TRAEFIK_DASHBOARD_USERNAME}:${TRAEFIK_DASHBOARD_PASSWORD}"
      "traefik.http.routers.traefik.middlewares": "traefik-dashboard-auth"
    networks:
      - student-club-web-network

  backend:
    image: "student-club-web-backend:latest"
    container_name: "student-club-web-backend"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend:/app
    depends_on:
      - traefik
      - mongodb
    networks:
      - student-club-web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: "student-club-web-frontend:latest"
    container_name: "student-club-web-frontend"
    environment:
      - SITE_HOSTNAME=${SITE_HOSTNAME}
      - BACKEND_URL=${BACKEND_URL}
      - PORT=${PORT}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_MEDIUM_URL=${NEXT_PUBLIC_MEDIUM_URL}
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_MEDIUM_URL: ${NEXT_PUBLIC_MEDIUM_URL}
    tty: true
    volumes:
      - ./frontend:/app
      - ./frontend/public:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${SITE_HOSTNAME:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=${PORT}"
    depends_on:
      - backend
    networks:
      - student-club-web-network

  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    ports:
      - "27017:${MONGODB_PORT}"
    command: [ "mongod", "--bind_ip_all" ]
    volumes:
      - mongodb-data:/data/db
    networks:
      - student-club-web-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data:
    driver: local

networks:
  student-club-web-network:
    driver: bridge
    ### if you want to use your docker network
    #external: true
    #name: your-docker-network-name
