name: Deploy Docker to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e  # Exit on any error
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            git fetch origin main
            git reset --hard origin/main
            docker compose build mongodb traefik commbuilder-backend            
            docker compose up -d mongodb traefik commbuilder-backend
            docker image prune -f
            docker compose ps